### PR TITLE
support Matrix.reshape function

### LINKED ISSUE #13: It would be nice to have Matrix.reshape
It would be something like numpy.reshape

```
> var linearAlgebra = require('linear-algebra')();
undefined
> var Matrix = linearAlgebra.Matrix;
undefined
> Matrix.reshape([1, 2, 5, 3, 4, 6, 5, 6, 7, 7, 8, 8], 4, 3);
{ data: [ [ 1, 2, 5 ], [ 3, 4, 6 ], [ 5, 6, 7 ], [ 7, 8, 8 ] ],
  rows: 4,
  cols: 3 }
> Matrix.reshape([1, 2, 5, 3, 4, 6, 5, 6, 7, 7, 8, 8], 3, 4);
{ data: [ [ 1, 2, 5, 3 ], [ 4, 6, 5, 6 ], [ 7, 7, 8, 8 ] ],
  rows: 3,
  cols: 4 }
```

### PR DESCRIPTION
**Pull request by yujiosaka**
close #13

### CODE REVIEW

**Comment by hiddentao** [comment]
Good idea. I'm wondering, perhaps the reshape method should be on the `Matrix` prototype. In other words, you first build a `Matrix` and you can `reshape` it, which will return a newly constructed `Matrix`. What are your thoughts on this?

**Comment by yujiosaka** [comment]
@hiddentao 
If it's on the `Vector` prototype, then it sounds a good idea to me.
The problem is that `Matrix` has two dimensions, so we don't know how how to reshape from it.
For example, we may reshape from rows to cols and vice versa.

This is why numpy.reshape only accepts array like object for it's argument,
even though the library usually works with any dimensions.

**Comment by hiddentao** [comment]
Ok. I think it should be on `Matrix` since it produces a matrix and it should be called `reshapeFrom`. It should return a new `Matrix` instance:

```js
Matrix.reshapeFrom([1,2,3,4,5,6],2,3).toArray();
// [[1,2,3],[4,5,6]]
```

Agree?

**Comment by yujiosaka** [comment]
Perfectly Agreed!!

**Comment by yujiosaka** [comment]
@hiddentao pushed!

**Comment by hiddentao** [comment]
Thanks.

**Pull request merged**
